services:
  - type: web
    name: build-a-3d-animated-cafe
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18